[tool.poetry]
name = "weather-prodgect"
version = "0.1.0"
description = ""
authors = ["Vasya <vasya130393@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
